### ISSUE TITLE
How do we even use it? Is it still maintained?

### ISSUE THREAD

**Issue by 7thghoul** [NoNoTeal/mitsuku-ai-api#1]

**Comment by NoNoTeal** [comment]
Usually the way you'd use it is by installing packages and editing the query variable, then running `node .`, but after checking my code out they've moved their site and added several constrants:

- Forces you to accept some terms
- No bot key from what I can see that I can scrape
- Makes you create an account when you request enough

The old site has some constraints as well, like consistent error messages. I'm probably not gonna maintain this project. There's better results if you use something like a cleverbot scraper. This project was just experimenting and poking at this api.
